import { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import {BrowserRouter as Router,Route,Switch} from 'react-router-dom'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Your Deals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
    </div>
  )
}

export async function getServerSideProps({ req }) {

  return {
      redirect: {
          permanent: false,
          destination: "/portail",
      },
      props:{message:"redirect"},
  }
 
 
}



